---
title: chart test
author: ''
date: '2020-04-13'
slug: chart-test
categories: []
tags: []
---

```{r, include=FALSE, echo=FALSE}
require(data.table)
require(purrr)
require(ggplot2)
require(reshape2)
require(lubridate)
require(plotly)
require(highcharter)

path = "../COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/"

#getwd()
# tsd<-fread("../COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
# ts

tsd<-fread("C:/Users/victor.enciso/Documents_notOneDrive/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
#tsd

tsdd<-melt(tsd[`4/11/20` > 1000],c("Country/Region","Province/State","Lat","Long"))
tsdd[,variable:=lubridate::mdy(variable)]

```

```{r, echo=FALSE, warning=FALSE}
tsdd %>% 
  hchart(., 
         type = "line", 
         hcaes(x = variable, 
               y = value, 
               group = `Country/Region`)) %>% 
  hc_yAxis(opposite = FALSE,
           labels = list(format = "{value}")) %>% 
  hc_tooltip(pointFormat = '{point.x:%Y-%m-%d}
                             {point.y: .4f}%')
```

```{r, echo=FALSE, warning=FALSE}
p<-ggplot(tsdd[variable>"2020-03-25"],aes(x=variable, y=value, group=`Country/Region`, colour=`Country/Region`)) + geom_line() + geom_point()

```

```{r}
ggplotly(p)
```

