---
title: Charts again
author: ''
date: '2020-04-19'
slug: charts-again
categories: []
tags: []
---

Comparing plotly to Highcharts

```{r,include=FALSE, echo=FALSE}
library(utils)
require(data.table)
require(dplyr)
require(ggplot2)
require(lubridate)
require(plotly)
require(highcharter)

#read the Dataset sheet into “R”. The dataset will be called "data".
cov <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
cov<-data.table(cov)
cov[,dateRep:=dmy(dateRep)]
setnames(cov,"countriesAndTerritories","country")
cov<-cov[order(country,dateRep)]
cov[,`:=`(cumCases=cumsum(cases),cumDeaths=cumsum(deaths)),country]
cov[,laggedDeaths := shift(deaths),country]
cov[,deathChange := (deaths-laggedDeaths)/laggedDeaths]
cov
```

```{r, echo=FALSE, warning=FALSE}
p<-ggplot(cov[cumDeaths>500 & country!="China"],aes(x=dateRep,y=log(deaths), colour=country, group=country)) + geom_line() + geom_point() + theme_bw()
```

```{r,echo=FALSE}
ggplotly(p)
```


```{r, echo=FALSE, warning=FALSE}
cov[cumDeaths>500 & country!="China"] %>% hchart(., 
              type = "line", 
              hcaes(x = dateRep, 
                    y = log(deaths), 
                    group = country)) %>% 
  hc_yAxis(opposite = FALSE,
           labels = list(format = "{value}")) %>% 
  hc_tooltip(pointFormat = '{point.x:%Y-%m-%d}
                             {point.y: .4f}%')
```


```{r,include=FALSE, echo=FALSE}
fp<-cov[cumDeaths>=100]
fp[,index:=seq(1,.N),country]
```

```{r, echo=FALSE, warning=FALSE}
p<-ggplot(fp,aes(x=index, y=log(cumDeaths), group=country, colour=country)) + geom_line() + geom_point() + theme_bw()
```

```{r, echo=FALSE}
py<-ggplotly(p)
py
```




```{r, echo=FALSE, warning=FALSE}
fp %>% hchart(., 
         type = "line", 
         hcaes(x = index, 
               y = log(cumDeaths), 
               group = country)) %>% 
  hc_yAxis(opposite = FALSE,
           labels = list(format = "{value}")) %>% 
  hc_tooltip(pointFormat = '{point.x:%Y-%m-%d}
                             {point.y: .4f}%')

```

